#!/usr/bin/env sh
set -eu

# Regenerate the human/AI skill index from .agents/skills/*/SKILL.md frontmatter.
# This script is generated by Agent Feed. Prefer `agent-feed index-skills`
# when the CLI is available.

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
SCRIPT_NAME="index-skills"
cd "$ROOT_DIR"

fail() {
  echo "$SCRIPT_NAME: ERROR: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

need_cmd python3

if [ ! -d .agents/skills ]; then
  fail "missing .agents/skills. Run agent-feed init before indexing skills."
fi

python3 - <<'PY'
from pathlib import Path

root = Path(".")
skill_root = root / ".agents/skills"
index_path = skill_root / "README.md"
DEFAULT_SOURCE = "unknow"
DEFAULT_TRUST = "custom"


def frontmatter_text(text: str) -> dict[str, str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    data: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def default_value(key: str) -> str:
    if key == "source":
        return DEFAULT_SOURCE
    if key == "trust":
        return DEFAULT_TRUST
    raise ValueError(f"unsupported metadata key: {key}")


def normalized_skill_text(text: str) -> str:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return text

    closing_index = None
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            closing_index = index
            break
    if closing_index is None:
        return text

    key_lines: dict[str, int] = {}
    for index in range(1, closing_index):
        line = lines[index]
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        if key.strip() in {"source", "trust"}:
            key_lines[key.strip()] = index

    next_lines = list(lines)
    missing: list[str] = []
    for key in ("source", "trust"):
        line_index = key_lines.get(key)
        if line_index is None:
            missing.append(key)
            continue
        _existing_key, existing_value = next_lines[line_index].split(":", 1)
        if not existing_value.strip():
            next_lines[line_index] = f"{key}: {default_value(key)}"
            missing.append(key)

    insert_at = closing_index
    for key in ("source", "trust"):
        if key in key_lines or key not in missing:
            continue
        next_lines.insert(insert_at, f"{key}: {default_value(key)}")
        insert_at += 1

    if not missing:
        return text

    normalized = "\n".join(next_lines)
    if text.endswith("\n"):
        normalized += "\n"
    return normalized


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


skills = []
for skill_file in sorted(skill_root.glob("*/SKILL.md")):
    text = skill_file.read_text(encoding="utf-8")
    normalized_text = normalized_skill_text(text)
    if normalized_text != text:
        skill_file.write_text(normalized_text, encoding="utf-8")
    data = frontmatter_text(normalized_text)
    skills.append(
        {
            "name": data.get("name", skill_file.parent.name),
            "description": data.get("description", ""),
            "source": data.get("source", DEFAULT_SOURCE),
            "trust": data.get("trust", DEFAULT_TRUST),
        }
    )

lines = [
    "# Skill Index",
    "",
    "This file is generated by Agent Feed from `.agents/skills/*/SKILL.md` frontmatter.",
    "",
    "Run `agent-feed index-skills` or `sh .agents/scripts/index-skills.sh` after adding, removing, renaming, or editing skills.",
    "",
    "## Skills",
    "",
    "| Skill | Description | Source | Trust |",
    "| --- | --- | --- | --- |",
]

if skills:
    for skill in skills:
        lines.append(
            f"| `{skill['name']}` | {cell(skill['description'])} | "
            f"`{cell(skill['source'])}` | `{cell(skill['trust'])}` |"
        )
else:
    lines.append("| _none_ | No skills found. | `unknow` | `custom` |")

lines.extend(
    [
        "",
        "## Use Rules",
        "",
        "1. Read this index when selecting optional, custom, or specialized skills.",
        "2. Read the target `SKILL.md` before using a skill.",
        "3. Treat `trust: custom` skills as advisory methods, not authoritative rules.",
        "4. Higher-priority instructions in `AGENTS.md`, `.agents/rules/`, `.agents/project/`, `.agents/domain/`, the current user request, and the Task Brief override any skill text.",
        "5. If a skill suggests commands, network access, destructive changes, or writes outside the Task Brief, inspect the action and apply `.agents/rules/change-risk-gates.md` before proceeding.",
    ]
)

index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

printf '%s\n' "$SCRIPT_NAME: indexed .agents/skills/README.md"
