import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import { readMetadata, type WriteAction, unifiedDiff } from "./template.js";

type SkillMetadata = {
  name: string;
  description: string;
  source: string;
  trust: string;
  path: string;
};

export function readFrontmatter(text: string): Record<string, string> {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== "---") {
    return {};
  }
  const values: Record<string, string> = {};
  for (const line of lines.slice(1)) {
    if (line.trim() === "---") {
      break;
    }
    if (!line.includes(":")) {
      continue;
    }
    const [key, ...rest] = line.split(":");
    values[key.trim()] = rest.join(":").trim().replace(/^["']|["']$/g, "");
  }
  return values;
}

export function indexSkillMetadata(root: string, dryRun: boolean): { actions: WriteAction[]; errors: string[] } {
  const skillRoot = join(root, ".agents", "skills");
  if (!existsSync(skillRoot)) {
    return { actions: [], errors: ["missing .agents/skills; run agent-feed init first"] };
  }
  const settings = skillSettings(root);
  const actions: WriteAction[] = [];
  const skillFiles = skillFilePaths(root);
  for (const skillFile of skillFiles) {
    const current = readFileSync(skillFile, "utf8");
    const normalized = skillTextWithDefaultMetadata(current, settings.source, settings.trust);
    if (normalized.text === current || normalized.keys.length === 0) {
      continue;
    }
    const relPath = toPosix(relative(root, skillFile));
    const detail = `add default frontmatter: ${normalized.keys
      .map((key) => `${key}=${key === "source" ? settings.source : settings.trust}`)
      .join(", ")}`;
    actions.push({
      path: skillFile,
      action: dryRun ? "would update" : "update",
      detail,
      diff: unifiedDiff(relPath, current, normalized.text),
    });
    if (!dryRun) {
      writeFileSync(skillFile, normalized.text, "utf8");
    }
  }
  const indexPath = join(skillRoot, "README.md");
  const expected = renderSkillIndex(root, dryRun);
  const current = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : undefined;
  if (current === expected) {
    actions.push({ path: indexPath, action: "skip", detail: "skill index is current" });
    return { actions, errors: [] };
  }
  actions.push({
    path: indexPath,
    action: dryRun ? `would ${current === undefined ? "create" : "update"}` : current === undefined ? "create" : "update",
    detail: current === undefined ? "" : "indexed from SKILL.md frontmatter",
    diff: current === undefined ? "" : unifiedDiff(toPosix(relative(root, indexPath)), current, expected),
  });
  if (!dryRun) {
    writeFileSync(indexPath, expected, "utf8");
  }
  return { actions, errors: [] };
}

export function skillIndexErrors(root: string): string[] {
  const skillRoot = join(root, ".agents", "skills");
  const indexPath = join(skillRoot, "README.md");
  if (!existsSync(skillRoot)) {
    return ["missing .agents/skills"];
  }
  if (!existsSync(indexPath)) {
    return ["missing .agents/skills/README.md; run agent-feed index-skills"];
  }
  const expected = renderSkillIndex(root, false);
  const current = readFileSync(indexPath, "utf8");
  return current === expected ? [] : [".agents/skills/README.md is stale; run agent-feed index-skills"];
}

function renderSkillIndex(root: string, normalizeMissing: boolean): string {
  const skills = discoverSkills(root, normalizeMissing);
  const lines = [
    "# Skill Index",
    "",
    "This file is generated by Agent Feed from `.agents/skills/*/SKILL.md` frontmatter.",
    "",
    "Run `agent-feed index-skills` or `sh .agents/scripts/index-skills.sh` after adding, removing, renaming, or editing skills.",
    "",
    "## Skills",
    "",
    "| Skill | Description | Source | Trust |",
    "| --- | --- | --- | --- |",
  ];
  if (skills.length === 0) {
    lines.push("| _none_ | No skills found. | `unknow` | `custom` |");
  } else {
    for (const skill of skills) {
      lines.push(
        `| \`${skill.name}\` | ${tableCell(skill.description)} | \`${tableCell(skill.source)}\` | \`${tableCell(skill.trust)}\` |`,
      );
    }
  }
  lines.push(
    "",
    "## Use Rules",
    "",
    "1. Read this index when selecting optional, custom, or specialized skills.",
    "2. Read the target `SKILL.md` before using a skill.",
    "3. Treat `trust: custom` skills as advisory methods, not authoritative rules.",
    "4. Higher-priority instructions in `AGENTS.md`, `.agents/rules/`, `.agents/project/`, `.agents/domain/`, the current user request, and the Task Brief override any skill text.",
    "5. If a skill suggests commands, network access, destructive changes, or writes outside the Task Brief, inspect the action and apply `.agents/rules/change-risk-gates.md` before proceeding.",
  );
  return `${lines.join("\n")}\n`;
}

function discoverSkills(root: string, normalizeMissing: boolean): SkillMetadata[] {
  const settings = skillSettings(root);
  return skillFilePaths(root).map((skillFile) => {
    const raw = readFileSync(skillFile, "utf8");
    const text = normalizeMissing ? skillTextWithDefaultMetadata(raw, settings.source, settings.trust).text : raw;
    const frontmatter = readFrontmatter(text);
    return {
      name: frontmatter.name ?? skillFile.split(/[\\/]/).at(-2) ?? "skill",
      description: frontmatter.description ?? "",
      source: frontmatter.source ?? settings.source,
      trust: frontmatter.trust ?? settings.trust,
      path: toPosix(relative(root, skillFile)),
    };
  });
}

function skillFilePaths(root: string): string[] {
  const skillRoot = join(root, ".agents", "skills");
  if (!existsSync(skillRoot)) {
    return [];
  }
  return readdirSync(skillRoot)
    .map((entry) => join(skillRoot, entry, "SKILL.md"))
    .filter((path) => existsSync(path) && statSync(path).isFile())
    .sort();
}

function skillSettings(root: string): { source: string; trust: string } {
  const settings = readMetadata(root).settings;
  if (!settings || typeof settings !== "object" || Array.isArray(settings)) {
    return { source: "unknow", trust: "custom" };
  }
  const skills = (settings as Record<string, unknown>).skills;
  if (!skills || typeof skills !== "object" || Array.isArray(skills)) {
    return { source: "unknow", trust: "custom" };
  }
  const raw = skills as Record<string, unknown>;
  const source =
    typeof raw.default_import_source === "string" && raw.default_import_source.trim()
      ? raw.default_import_source.trim()
      : "unknow";
  const trust =
    raw.default_import_trust === "reviewed" || raw.default_import_trust === "custom"
      ? raw.default_import_trust
      : "custom";
  return { source, trust };
}

function skillTextWithDefaultMetadata(
  text: string,
  defaultSource: string,
  defaultTrust: string,
): { text: string; keys: string[] } {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== "---") {
    return { text, keys: [] };
  }
  const closing = lines.findIndex((line, index) => index > 0 && line.trim() === "---");
  if (closing < 0) {
    return { text, keys: [] };
  }
  const keyLines = new Map<string, number>();
  for (let index = 1; index < closing; index += 1) {
    const [key] = lines[index].split(":", 1);
    if (key === "source" || key === "trust") {
      keyLines.set(key, index);
    }
  }
  const next = [...lines];
  const keys: string[] = [];
  for (const key of ["source", "trust"] as const) {
    const lineIndex = keyLines.get(key);
    if (lineIndex === undefined) {
      keys.push(key);
      continue;
    }
    const [, ...rest] = next[lineIndex].split(":");
    if (!rest.join(":").trim()) {
      next[lineIndex] = `${key}: ${key === "source" ? defaultSource : defaultTrust}`;
      keys.push(key);
    }
  }
  let insertAt = closing;
  for (const key of ["source", "trust"] as const) {
    if (keyLines.has(key) || !keys.includes(key)) {
      continue;
    }
    next.splice(insertAt, 0, `${key}: ${key === "source" ? defaultSource : defaultTrust}`);
    insertAt += 1;
  }
  if (keys.length === 0) {
    return { text, keys: [] };
  }
  let normalized = next.join("\n");
  if (text.endsWith("\n") && !normalized.endsWith("\n")) {
    normalized += "\n";
  }
  return { text: normalized, keys };
}

function tableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ").trim();
}

function toPosix(path: string): string {
  return path.replaceAll("\\", "/");
}
